/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => JournalsAwareRolloverPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/settings.ts
var DEFAULT_SETTINGS = {
  enabledJournals: "",
  autoRolloverOnCreate: true,
  deleteFromPrevious: false,
  rolloverChildren: true,
  removeEmptyTodos: true,
  doneStatusMarkers: "xX-",
  headingPattern: "^#{1,6}\\s+.*TODOS\\s*$",
  headingFallback: "bottom",
  skipDuplicates: true,
  showNotice: true
};
function parseEnabledJournals(value) {
  return value.split(",").map((s) => s.trim()).filter((s) => s.length > 0);
}

// src/todoParser.ts
var BULLET_SYMBOLS = ["-", "*", "+"];
function parseIntoChars(content) {
  const SegmenterCtor = Intl.Segmenter;
  if (typeof Intl !== "undefined" && SegmenterCtor) {
    const segmenter = new SegmenterCtor("en", { granularity: "grapheme" });
    return Array.from(segmenter.segment(content), (s) => s.segment);
  }
  return Array.from(content);
}
var TodoParser = class {
  constructor(lines, withChildren, doneStatusMarkers) {
    this.lines = lines;
    this.withChildren = withChildren;
    this.doneStatusMarkers = doneStatusMarkers ? parseIntoChars(doneStatusMarkers) : ["x", "X", "-"];
  }
  /** A line is an (unfinished) todo when it is a checkbox whose single-grapheme marker is not a done marker. */
  isTodo(s) {
    const bulletClass = BULLET_SYMBOLS.map((b) => "\\" + b).join("");
    const match = s.match(new RegExp(`\\s*[${bulletClass}] \\[(.+?)\\]`));
    if (!match)
      return false;
    const checkboxContent = match[1];
    const contentChars = parseIntoChars(checkboxContent);
    if (contentChars.length !== 1)
      return false;
    const graphemeModifiers = ["\u202E", "\u200B", "\u200C", "\u200D"];
    if (contentChars.some((c) => graphemeModifiers.includes(c)))
      return false;
    const hasDoneMarker = contentChars.some((c) => this.doneStatusMarkers.includes(c));
    return !hasDoneMarker;
  }
  getIndentation(l) {
    return this.lines[l].search(/\S/);
  }
  isChildOf(parentLinum, linum) {
    if (parentLinum >= this.lines.length || linum >= this.lines.length)
      return false;
    return this.getIndentation(linum) > this.getIndentation(parentLinum);
  }
  hasChildren(l) {
    if (l + 1 >= this.lines.length)
      return false;
    return this.getIndentation(l + 1) > this.getIndentation(l);
  }
  getChildren(parentLinum) {
    const children = [];
    let next = parentLinum + 1;
    while (this.isChildOf(parentLinum, next)) {
      children.push(this.lines[next]);
      next++;
    }
    return children;
  }
  getTodos() {
    let todos = [];
    for (let l = 0; l < this.lines.length; l++) {
      const line = this.lines[l];
      if (this.isTodo(line)) {
        todos.push(line);
        if (this.withChildren && this.hasChildren(l)) {
          const cs = this.getChildren(l);
          todos = [...todos, ...cs];
          l += cs.length;
        }
      }
    }
    return todos;
  }
};
function getUnfinishedTodos(content, options) {
  const lines = content.split(/\r?\n|\r|\n/g);
  const parser = new TodoParser(lines, options.withChildren, options.doneStatusMarkers);
  let todos = parser.getTodos();
  if (options.removeEmptyTodos) {
    todos = todos.filter((line) => {
      const trimmed = (line || "").trim();
      return trimmed !== "- [ ]" && trimmed !== "- [  ]";
    });
  }
  return todos;
}

// src/journal.ts
var import_obsidian = require("obsidian");
var DATE_FORMATS = ["YYYY-MM-DD", import_obsidian.moment.ISO_8601];
function toMoment(value) {
  if (value == null)
    return null;
  if (value instanceof Date) {
    const m2 = (0, import_obsidian.moment)(value);
    return m2.isValid() ? m2.startOf("day") : null;
  }
  const m = (0, import_obsidian.moment)(String(value), DATE_FORMATS, true);
  return m.isValid() ? m.startOf("day") : null;
}
function readFrontmatterRaw(content) {
  const out = {};
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match)
    return out;
  for (const line of match[1].split(/\r?\n/)) {
    const kv = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (kv) {
      out[kv[1]] = kv[2].trim().replace(/^["']|["']$/g, "");
    }
  }
  return out;
}
function journalInfoFromFrontmatter(fm) {
  if (!fm)
    return null;
  const date = toMoment(fm["journal-date"]);
  if (!date)
    return null;
  const journal = fm["journal"] != null ? String(fm["journal"]) : "";
  return { journal, date, dateString: date.format("YYYY-MM-DD") };
}
async function getJournalInfo(app, file) {
  var _a;
  try {
    const content = await app.vault.read(file);
    const fm = readFrontmatterRaw(content);
    const info = journalInfoFromFrontmatter(fm);
    if (info)
      return info;
  } catch (e) {
  }
  const cached = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
  return journalInfoFromFrontmatter(cached);
}
function findPreviousJournalNote(app, currentFile, info, allowedJournals) {
  var _a;
  let best = null;
  let bestDate = null;
  for (const file of app.vault.getMarkdownFiles()) {
    if (file.path === currentFile.path)
      continue;
    const fm = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    const candidate = journalInfoFromFrontmatter(fm);
    if (!candidate)
      continue;
    if (info.journal && candidate.journal !== info.journal)
      continue;
    if (allowedJournals.length > 0 && !allowedJournals.includes(candidate.journal))
      continue;
    if (!candidate.date.isBefore(info.date, "day"))
      continue;
    if (!bestDate || candidate.date.isAfter(bestDate)) {
      bestDate = candidate.date;
      best = file;
    }
  }
  return best;
}

// src/main.ts
var READY_TIMEOUT_MS = 6e3;
var READY_POLL_MS = 200;
var RECENTLY_HANDLED_MS = 8e3;
var JournalsAwareRolloverPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.recentlyHandled = /* @__PURE__ */ new Map();
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new JournalsAwareRolloverSettingTab(this.app, this));
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (!this.settings.autoRolloverOnCreate)
          return;
        if (!(file instanceof import_obsidian2.TFile) || file.extension !== "md")
          return;
        void this.handleCreate(file);
      })
    );
    this.addCommand({
      id: "rollover-into-current-note",
      name: "Roll over todos into the current note",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!file || file.extension !== "md")
          return false;
        if (!checking) {
          void this.rolloverInto(file, { manual: true });
        }
        return true;
      }
    });
  }
  onunload() {
    this.recentlyHandled.clear();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // --- Auto path ----------------------------------------------------------
  wasRecentlyHandled(path) {
    const now = Date.now();
    for (const [p, t] of this.recentlyHandled) {
      if (now - t > RECENTLY_HANDLED_MS)
        this.recentlyHandled.delete(p);
    }
    return this.recentlyHandled.has(path);
  }
  async handleCreate(file) {
    if (this.wasRecentlyHandled(file.path))
      return;
    const ready = await this.waitUntilReady(file);
    if (!ready)
      return;
    this.recentlyHandled.set(file.path, Date.now());
    await this.rolloverInto(file, { manual: false });
  }
  /**
   * Wait until the new note has `journal-date` frontmatter and (ideally) the
   * target heading rendered, so we don't insert before the template writes it.
   * Resolves true once it looks like a journal note, false on timeout.
   */
  async waitUntilReady(file) {
    const headingRe = this.compileHeadingRegex();
    const deadline = Date.now() + READY_TIMEOUT_MS;
    let sawJournalDate = false;
    while (Date.now() < deadline) {
      let content = "";
      try {
        content = await this.app.vault.read(file);
      } catch (e) {
        return false;
      }
      const fm = readFrontmatterRaw(content);
      const isJournal = fm["journal-date"] != null && fm["journal-date"] !== "";
      if (isJournal) {
        sawJournalDate = true;
        const headingPresent = headingRe ? headingRe.test(content) : false;
        if (headingPresent || this.settings.headingFallback !== "skip") {
          if (headingPresent)
            return true;
        }
      }
      await sleep(READY_POLL_MS);
    }
    return sawJournalDate;
  }
  // --- Core ---------------------------------------------------------------
  compileHeadingRegex() {
    try {
      return new RegExp(this.settings.headingPattern, "i");
    } catch (e) {
      return null;
    }
  }
  async rolloverInto(file, opts) {
    const info = await getJournalInfo(this.app, file);
    if (!info) {
      if (opts.manual) {
        new import_obsidian2.Notice(
          "Journal Aware Rollover: the current note has no `journal-date` frontmatter, so it isn't a Journals note."
        );
      }
      return;
    }
    const allowed = parseEnabledJournals(this.settings.enabledJournals);
    if (allowed.length > 0 && info.journal && !allowed.includes(info.journal)) {
      if (opts.manual) {
        new import_obsidian2.Notice(
          `Journal Aware Rollover: journal "${info.journal}" is not in the enabled list.`
        );
      }
      return;
    }
    const previous = findPreviousJournalNote(this.app, file, info, allowed);
    if (!previous) {
      if (opts.manual)
        new import_obsidian2.Notice("Journal Aware Rollover: no earlier journal note found.");
      return;
    }
    const previousContent = await this.app.vault.read(previous);
    let todos = getUnfinishedTodos(previousContent, {
      withChildren: this.settings.rolloverChildren,
      doneStatusMarkers: this.settings.doneStatusMarkers,
      removeEmptyTodos: this.settings.removeEmptyTodos
    });
    if (todos.length === 0) {
      if (opts.manual) {
        new import_obsidian2.Notice(`Journal Aware Rollover: no unfinished todos in ${previous.basename}.`);
      }
      return;
    }
    const currentContent = await this.app.vault.read(file);
    if (this.settings.skipDuplicates) {
      const existing = new Set(
        currentContent.split(/\r?\n/).map((l) => l.trim())
      );
      todos = todos.filter((line) => !existing.has(line.trim()));
      if (todos.length === 0) {
        if (opts.manual) {
          new import_obsidian2.Notice("Journal Aware Rollover: all todos are already present in this note.");
        }
        return;
      }
    }
    const inserted = this.insertTodos(currentContent, todos);
    if (inserted == null) {
      if (opts.manual) {
        new import_obsidian2.Notice(
          "Journal Aware Rollover: target heading not found and fallback is set to skip."
        );
      }
      return;
    }
    await this.app.vault.modify(file, inserted);
    if (this.settings.deleteFromPrevious) {
      await this.deleteFromPrevious(previous, todos);
    }
    if (this.settings.showNotice) {
      const n = todos.length;
      new import_obsidian2.Notice(
        `Journal Aware Rollover: ${n} todo${n > 1 ? "s" : ""} from ${previous.basename}.`
      );
    }
  }
  /**
   * Insert todos beneath the first heading matching the pattern, or at the
   * configured fallback position. Returns new content, or null if it should
   * be skipped.
   */
  insertTodos(content, todos) {
    const lines = content.split(/\r?\n/);
    const headingRe = this.compileHeadingRegex();
    let headingIndex = -1;
    if (headingRe) {
      for (let i = 0; i < lines.length; i++) {
        if (/^#{1,6}\s/.test(lines[i]) && headingRe.test(lines[i])) {
          headingIndex = i;
          break;
        }
      }
    }
    if (headingIndex >= 0) {
      lines.splice(headingIndex + 1, 0, ...todos);
      return lines.join("\n");
    }
    const fallback = this.settings.headingFallback;
    if (fallback === "skip")
      return null;
    if (fallback === "top") {
      const bodyStart = frontmatterEndIndex(lines);
      lines.splice(bodyStart, 0, ...todos);
      return lines.join("\n");
    }
    const block = todos.join("\n");
    return content.endsWith("\n") || content.length === 0 ? content + block + "\n" : content + "\n" + block + "\n";
  }
  async deleteFromPrevious(previous, rolled) {
    const content = await this.app.vault.read(previous);
    const remove = new Set(rolled);
    const kept = content.split(/\r?\n/).filter((line) => !remove.has(line));
    await this.app.vault.modify(previous, kept.join("\n"));
  }
};
function frontmatterEndIndex(lines) {
  if (lines[0] !== "---")
    return 0;
  for (let i = 1; i < lines.length; i++) {
    if (lines[i] === "---")
      return i + 1;
  }
  return 0;
}
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
var JournalsAwareRolloverSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Automatic rollover on new note").setDesc(
      "Roll over todos automatically when the Journals plugin creates a new note. The manual command is always available regardless of this setting."
    ).addToggle(
      (t) => t.setValue(this.plugin.settings.autoRolloverOnCreate).onChange(async (v) => {
        this.plugin.settings.autoRolloverOnCreate = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Delete todos from the previous note").setDesc(
      "After copying todos forward, remove them from the previous note (move instead of copy). Destructive \u2014 leave off to duplicate them safely."
    ).addToggle(
      (t) => t.setValue(this.plugin.settings.deleteFromPrevious).onChange(async (v) => {
        this.plugin.settings.deleteFromPrevious = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Roll over child items").setDesc("Also carry indented lines nested beneath an unfinished todo.").addToggle(
      (t) => t.setValue(this.plugin.settings.rolloverChildren).onChange(async (v) => {
        this.plugin.settings.rolloverChildren = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Skip empty todos").setDesc("Do not roll over bare `- [ ]` items that have no text.").addToggle(
      (t) => t.setValue(this.plugin.settings.removeEmptyTodos).onChange(async (v) => {
        this.plugin.settings.removeEmptyTodos = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Skip todos already in the new note").setDesc("Avoid inserting a todo whose exact text already exists in the target note.").addToggle(
      (t) => t.setValue(this.plugin.settings.skipDuplicates).onChange(async (v) => {
        this.plugin.settings.skipDuplicates = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Target heading pattern").setDesc(
      "Case-insensitive regex matched against heading lines. Todos are inserted beneath the first match. Default matches headings ending in TODOS (e.g. `## FRIDAY TODOS`)."
    ).addText(
      (t) => t.setPlaceholder(DEFAULT_SETTINGS.headingPattern).setValue(this.plugin.settings.headingPattern).onChange(async (v) => {
        this.plugin.settings.headingPattern = v || DEFAULT_SETTINGS.headingPattern;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("If the heading is not found").setDesc("Where to place todos when no heading matches the pattern.").addDropdown(
      (d) => d.addOptions({
        bottom: "Append to bottom of note",
        top: "Insert at top (after frontmatter)",
        skip: "Skip rollover"
      }).setValue(this.plugin.settings.headingFallback).onChange(async (v) => {
        this.plugin.settings.headingFallback = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Done status markers").setDesc('Characters inside `[ ]` that mean a todo is complete. Default "xX-".').addText(
      (t) => t.setPlaceholder(DEFAULT_SETTINGS.doneStatusMarkers).setValue(this.plugin.settings.doneStatusMarkers).onChange(async (v) => {
        this.plugin.settings.doneStatusMarkers = v || DEFAULT_SETTINGS.doneStatusMarkers;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Limit to journals").setDesc(
      "Comma-separated Journals names to act on (matched against the `journal` frontmatter field). Leave empty to act on every note that has a `journal-date`."
    ).addText(
      (t) => t.setPlaceholder("e.g. DailyNote, WeeklyNote").setValue(this.plugin.settings.enabledJournals).onChange(async (v) => {
        this.plugin.settings.enabledJournals = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Show notice after rollover").setDesc("Display a short summary each time todos are rolled over.").addToggle(
      (t) => t.setValue(this.plugin.settings.showNotice).onChange(async (v) => {
        this.plugin.settings.showNotice = v;
        await this.plugin.saveSettings();
      })
    );
  }
};
