/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => JournalsAwareRolloverPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/settings.ts
var DEFAULT_SETTINGS = {
  enabledJournals: "",
  autoRolloverOnCreate: true,
  deleteFromPrevious: false,
  rolloverChildren: true,
  removeEmptyTodos: true,
  doneStatusMarkers: "xX-",
  headingPattern: "^#{1,6}\\s+.*TODOS\\s*$",
  headingFallback: "bottom",
  skipDuplicates: true,
  showNotice: true
};
function parseEnabledJournals(value) {
  return value.split(",").map((s) => s.trim()).filter((s) => s.length > 0);
}

// src/todoParser.ts
var BULLET_SYMBOLS = ["-", "*", "+"];
function parseIntoChars(content) {
  const SegmenterCtor = Intl.Segmenter;
  if (SegmenterCtor) {
    const segmenter = new SegmenterCtor("en", { granularity: "grapheme" });
    return Array.from(segmenter.segment(content), (s) => s.segment);
  }
  return Array.from(content);
}
var TodoParser = class {
  constructor(lines, withChildren, doneStatusMarkers) {
    this.lines = lines;
    this.withChildren = withChildren;
    this.doneStatusMarkers = doneStatusMarkers ? parseIntoChars(doneStatusMarkers) : ["x", "X", "-"];
  }
  /** A line is an (unfinished) todo when it is a checkbox whose single-grapheme marker is not a done marker. */
  isTodo(s) {
    const bulletClass = BULLET_SYMBOLS.map((b) => "\\" + b).join("");
    const match = s.match(new RegExp(`\\s*[${bulletClass}] \\[(.+?)\\]`));
    if (!match)
      return false;
    const checkboxContent = match[1];
    const contentChars = parseIntoChars(checkboxContent);
    if (contentChars.length !== 1)
      return false;
    const graphemeModifiers = ["\u202E", "\u200B", "\u200C", "\u200D"];
    if (contentChars.some((c) => graphemeModifiers.includes(c)))
      return false;
    const hasDoneMarker = contentChars.some((c) => this.doneStatusMarkers.includes(c));
    return !hasDoneMarker;
  }
  getIndentation(l) {
    return this.lines[l].search(/\S/);
  }
  isChildOf(parentLinum, linum) {
    if (parentLinum >= this.lines.length || linum >= this.lines.length)
      return false;
    return this.getIndentation(linum) > this.getIndentation(parentLinum);
  }
  hasChildren(l) {
    if (l + 1 >= this.lines.length)
      return false;
    return this.getIndentation(l + 1) > this.getIndentation(l);
  }
  getChildren(parentLinum) {
    const children = [];
    let next = parentLinum + 1;
    while (this.isChildOf(parentLinum, next)) {
      children.push(this.lines[next]);
      next++;
    }
    return children;
  }
  getTodos() {
    let todos = [];
    for (let l = 0; l < this.lines.length; l++) {
      const line = this.lines[l];
      if (this.isTodo(line)) {
        todos.push(line);
        if (this.withChildren && this.hasChildren(l)) {
          const cs = this.getChildren(l);
          todos = [...todos, ...cs];
          l += cs.length;
        }
      }
    }
    return todos;
  }
};
function getUnfinishedTodos(content, options) {
  const lines = content.split(/\r?\n|\r|\n/g);
  const parser = new TodoParser(lines, options.withChildren, options.doneStatusMarkers);
  let todos = parser.getTodos();
  if (options.removeEmptyTodos) {
    todos = todos.filter((line) => {
      const trimmed = (line || "").trim();
      return trimmed !== "- [ ]" && trimmed !== "- [  ]";
    });
  }
  return todos;
}

// src/journal.ts
var import_obsidian = require("obsidian");
var M = import_obsidian.moment;
var DATE_FORMATS = ["YYYY-MM-DD", M.ISO_8601];
function toMoment(value) {
  if (value == null)
    return null;
  if (value instanceof Date) {
    const m2 = M(value);
    return m2.isValid() ? m2.startOf("day") : null;
  }
  const m = M(String(value), DATE_FORMATS, true);
  return m.isValid() ? m.startOf("day") : null;
}
function readFrontmatterRaw(content) {
  const out = {};
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match)
    return out;
  for (const line of match[1].split(/\r?\n/)) {
    const kv = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (kv) {
      out[kv[1]] = kv[2].trim().replace(/^["']|["']$/g, "");
    }
  }
  return out;
}
function journalInfoFromFrontmatter(fm) {
  if (!fm)
    return null;
  const date = toMoment(fm["journal-date"]);
  if (!date)
    return null;
  const journal = fm["journal"] != null ? String(fm["journal"]) : "";
  return { journal, date, dateString: date.format("YYYY-MM-DD") };
}
async function getJournalInfo(app, file) {
  var _a;
  try {
    const content = await app.vault.read(file);
    const fm = readFrontmatterRaw(content);
    const info = journalInfoFromFrontmatter(fm);
    if (info)
      return info;
  } catch (e) {
  }
  const cached = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
  return journalInfoFromFrontmatter(cached);
}
function findPreviousJournalNote(app, currentFile, info, allowedJournals) {
  var _a;
  let best = null;
  let bestDate = null;
  for (const file of app.vault.getMarkdownFiles()) {
    if (file.path === currentFile.path)
      continue;
    const fm = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    const candidate = journalInfoFromFrontmatter(fm);
    if (!candidate)
      continue;
    if (info.journal && candidate.journal !== info.journal)
      continue;
    if (allowedJournals.length > 0 && !allowedJournals.includes(candidate.journal))
      continue;
    if (!candidate.date.isBefore(info.date, "day"))
      continue;
    if (!bestDate || candidate.date.isAfter(bestDate)) {
      bestDate = candidate.date;
      best = file;
    }
  }
  return best;
}

// src/main.ts
var READY_TIMEOUT_MS = 6e3;
var READY_POLL_MS = 200;
var RECENTLY_HANDLED_MS = 8e3;
var JournalsAwareRolloverPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.recentlyHandled = /* @__PURE__ */ new Map();
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new JournalsAwareRolloverSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      this.registerEvent(
        this.app.vault.on("create", (file) => {
          if (!this.settings.autoRolloverOnCreate)
            return;
          if (!(file instanceof import_obsidian2.TFile) || file.extension !== "md")
            return;
          void this.handleCreate(file);
        })
      );
    });
    this.addCommand({
      id: "rollover-into-current-note",
      name: "Roll over todos into the current note",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!file || file.extension !== "md")
          return false;
        if (!checking) {
          void this.rolloverInto(file, { manual: true });
        }
        return true;
      }
    });
  }
  onunload() {
    this.recentlyHandled.clear();
  }
  async loadSettings() {
    const saved = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, saved);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // --- Auto path ----------------------------------------------------------
  wasRecentlyHandled(path) {
    const now = Date.now();
    for (const [p, t] of this.recentlyHandled) {
      if (now - t > RECENTLY_HANDLED_MS)
        this.recentlyHandled.delete(p);
    }
    return this.recentlyHandled.has(path);
  }
  async handleCreate(file) {
    if (this.wasRecentlyHandled(file.path))
      return;
    const ready = await this.waitUntilReady(file);
    if (!ready)
      return;
    this.recentlyHandled.set(file.path, Date.now());
    await this.rolloverInto(file, { manual: false });
  }
  /**
   * Wait until the new note has `journal-date` frontmatter and (ideally) the
   * target heading rendered, so we don't insert before the template writes it.
   * Resolves true once it looks like a journal note, false on timeout.
   */
  async waitUntilReady(file) {
    const headingRe = this.compileHeadingRegex();
    const deadline = Date.now() + READY_TIMEOUT_MS;
    let sawJournalDate = false;
    while (Date.now() < deadline) {
      let content = "";
      try {
        content = await this.app.vault.read(file);
      } catch (e) {
        return false;
      }
      const fm = readFrontmatterRaw(content);
      const isJournal = fm["journal-date"] != null && fm["journal-date"] !== "";
      if (isJournal) {
        sawJournalDate = true;
        const headingPresent = headingRe ? headingRe.test(content) : false;
        if (headingPresent || this.settings.headingFallback !== "skip") {
          if (headingPresent)
            return true;
        }
      }
      await sleep(READY_POLL_MS);
    }
    return sawJournalDate;
  }
  // --- Core ---------------------------------------------------------------
  compileHeadingRegex() {
    try {
      return new RegExp(this.settings.headingPattern, "i");
    } catch (e) {
      return null;
    }
  }
  async rolloverInto(file, opts) {
    const info = await getJournalInfo(this.app, file);
    if (!info) {
      if (opts.manual) {
        new import_obsidian2.Notice(
          "Journal Aware Rollover: the current note has no `journal-date` frontmatter, so it isn't a Journals note."
        );
      }
      return;
    }
    const allowed = parseEnabledJournals(this.settings.enabledJournals);
    if (allowed.length > 0 && info.journal && !allowed.includes(info.journal)) {
      if (opts.manual) {
        new import_obsidian2.Notice(
          `Journal Aware Rollover: journal "${info.journal}" is not in the enabled list.`
        );
      }
      return;
    }
    const previous = findPreviousJournalNote(this.app, file, info, allowed);
    if (!previous) {
      if (opts.manual)
        new import_obsidian2.Notice("Journal Aware Rollover: no earlier journal note found.");
      return;
    }
    const previousContent = await this.app.vault.read(previous);
    const todos = getUnfinishedTodos(previousContent, {
      withChildren: this.settings.rolloverChildren,
      doneStatusMarkers: this.settings.doneStatusMarkers,
      removeEmptyTodos: this.settings.removeEmptyTodos
    });
    if (todos.length === 0) {
      if (opts.manual) {
        new import_obsidian2.Notice(`Journal Aware Rollover: no unfinished todos in ${previous.basename}.`);
      }
      return;
    }
    const result = {
      outcome: "no-heading",
      rolled: []
    };
    await this.app.vault.process(file, (data) => {
      let toInsert = todos;
      if (this.settings.skipDuplicates) {
        const existing = new Set(data.split(/\r?\n/).map((l) => l.trim()));
        toInsert = toInsert.filter((line) => !existing.has(line.trim()));
        if (toInsert.length === 0) {
          result.outcome = "all-duplicates";
          return data;
        }
      }
      const inserted = this.insertTodos(data, toInsert);
      if (inserted == null) {
        result.outcome = "no-heading";
        return data;
      }
      result.outcome = "inserted";
      result.rolled = toInsert;
      return inserted;
    });
    if (result.outcome === "all-duplicates") {
      if (opts.manual) {
        new import_obsidian2.Notice("Journal Aware Rollover: all todos are already present in this note.");
      }
      return;
    }
    if (result.outcome === "no-heading") {
      if (opts.manual) {
        new import_obsidian2.Notice(
          "Journal Aware Rollover: target heading not found and fallback is set to skip."
        );
      }
      return;
    }
    if (this.settings.deleteFromPrevious) {
      await this.deleteFromPrevious(previous, result.rolled);
    }
    if (this.settings.showNotice) {
      const n = result.rolled.length;
      new import_obsidian2.Notice(
        `Journal Aware Rollover: ${n} todo${n > 1 ? "s" : ""} from ${previous.basename}.`
      );
    }
  }
  /**
   * Insert todos beneath the first heading matching the pattern, or at the
   * configured fallback position. Returns new content, or null if it should
   * be skipped.
   */
  insertTodos(content, todos) {
    const lines = content.split(/\r?\n/);
    const headingRe = this.compileHeadingRegex();
    let headingIndex = -1;
    if (headingRe) {
      for (let i = 0; i < lines.length; i++) {
        if (/^#{1,6}\s/.test(lines[i]) && headingRe.test(lines[i])) {
          headingIndex = i;
          break;
        }
      }
    }
    if (headingIndex >= 0) {
      lines.splice(headingIndex + 1, 0, ...todos);
      return lines.join("\n");
    }
    const fallback = this.settings.headingFallback;
    if (fallback === "skip")
      return null;
    if (fallback === "top") {
      const bodyStart = frontmatterEndIndex(lines);
      lines.splice(bodyStart, 0, ...todos);
      return lines.join("\n");
    }
    const block = todos.join("\n");
    return content.endsWith("\n") || content.length === 0 ? content + block + "\n" : content + "\n" + block + "\n";
  }
  async deleteFromPrevious(previous, rolled) {
    const remove = new Set(rolled);
    await this.app.vault.process(
      previous,
      (content) => content.split(/\r?\n/).filter((line) => !remove.has(line)).join("\n")
    );
  }
};
function frontmatterEndIndex(lines) {
  if (lines[0] !== "---")
    return 0;
  for (let i = 1; i < lines.length; i++) {
    if (lines[i] === "---")
      return i + 1;
  }
  return 0;
}
function sleep(ms) {
  return new Promise((resolve) => window.setTimeout(resolve, ms));
}
var COERCE_EMPTY_TO_DEFAULT = /* @__PURE__ */ new Set([
  "headingPattern",
  "doneStatusMarkers"
]);
var SETTING_DESCRIPTORS = [
  {
    key: "autoRolloverOnCreate",
    name: "Automatic rollover on new note",
    desc: "Roll over todos automatically when the Journals plugin creates a new note. The manual command is always available regardless of this setting.",
    control: { type: "toggle" }
  },
  {
    key: "deleteFromPrevious",
    name: "Delete todos from the previous note",
    desc: "After copying todos forward, remove them from the previous note (move instead of copy). Destructive \u2014 leave off to duplicate them safely.",
    control: { type: "toggle" }
  },
  {
    key: "rolloverChildren",
    name: "Roll over child items",
    desc: "Also carry indented lines nested beneath an unfinished todo.",
    control: { type: "toggle" }
  },
  {
    key: "removeEmptyTodos",
    name: "Skip empty todos",
    desc: "Do not roll over bare `- [ ]` items that have no text.",
    control: { type: "toggle" }
  },
  {
    key: "skipDuplicates",
    name: "Skip todos already in the new note",
    desc: "Avoid inserting a todo whose exact text already exists in the target note.",
    control: { type: "toggle" }
  },
  {
    key: "headingPattern",
    name: "Target heading pattern",
    desc: "Case-insensitive regex matched against heading lines. Todos are inserted beneath the first match. Default matches headings ending in TODOS (e.g. `## FRIDAY TODOS`).",
    control: {
      type: "text",
      placeholder: DEFAULT_SETTINGS.headingPattern,
      validate: (value) => {
        try {
          new RegExp(value || DEFAULT_SETTINGS.headingPattern, "i");
        } catch (e) {
          return "Not a valid regular expression.";
        }
      }
    }
  },
  {
    key: "headingFallback",
    name: "If the heading is not found",
    desc: "Where to place todos when no heading matches the pattern.",
    control: {
      type: "dropdown",
      options: {
        bottom: "Append to bottom of note",
        top: "Insert at top (after frontmatter)",
        skip: "Skip rollover"
      }
    }
  },
  {
    key: "doneStatusMarkers",
    name: "Done status markers",
    desc: 'Characters inside `[ ]` that mean a todo is complete. Default "xX-".',
    control: { type: "text", placeholder: DEFAULT_SETTINGS.doneStatusMarkers }
  },
  {
    key: "enabledJournals",
    name: "Limit to journals",
    desc: "Comma-separated Journals names to act on (matched against the `journal` frontmatter field). Leave empty to act on every note that has a `journal-date`.",
    control: { type: "text", placeholder: "e.g. DailyNote, WeeklyNote" }
  },
  {
    key: "showNotice",
    name: "Show notice after rollover",
    desc: "Display a short summary each time todos are rolled over.",
    control: { type: "toggle" }
  }
];
var JournalsAwareRolloverSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  /**
   * Declarative settings (Obsidian 1.13.0+). Returning a non-empty array makes
   * Obsidian render the tab from these definitions and index them for settings
   * search; `display()` below is then not called and only serves older builds.
   */
  getSettingDefinitions() {
    return SETTING_DESCRIPTORS.map((d) => ({
      name: d.name,
      desc: d.desc,
      control: buildControl(d)
    }));
  }
  getControlValue(key) {
    return this.plugin.settings[key];
  }
  async setControlValue(key, value) {
    this.store(key, value);
    await this.plugin.saveSettings();
  }
  /** Coerce and write one setting value into the settings object. */
  store(key, value) {
    const settings = this.plugin.settings;
    if (typeof value === "string" && value === "" && COERCE_EMPTY_TO_DEFAULT.has(key)) {
      settings[key] = DEFAULT_SETTINGS[key];
      return;
    }
    settings[key] = value;
  }
  /**
   * Imperative fallback for Obsidian < 1.13.0, where `getSettingDefinitions`
   * is not consulted. Renders the same descriptors with the classic API.
   */
  display() {
    const { containerEl } = this;
    containerEl.empty();
    for (const d of SETTING_DESCRIPTORS) {
      const setting = new import_obsidian2.Setting(containerEl).setName(d.name).setDesc(d.desc);
      this.addControl(setting, d);
    }
  }
  addControl(setting, d) {
    const key = d.key;
    const commit = async (value) => {
      this.store(key, value);
      await this.plugin.saveSettings();
    };
    switch (d.control.type) {
      case "toggle":
        setting.addToggle(
          (t) => t.setValue(this.plugin.settings[key]).onChange((v) => void commit(v))
        );
        break;
      case "dropdown": {
        const options = d.control.options;
        setting.addDropdown(
          (dd) => dd.addOptions(options).setValue(this.plugin.settings[key]).onChange((v) => void commit(v))
        );
        break;
      }
      case "text": {
        const placeholder = d.control.placeholder;
        setting.addText(
          (t) => t.setPlaceholder(placeholder).setValue(this.plugin.settings[key]).onChange((v) => void commit(v))
        );
        break;
      }
    }
  }
};
function buildControl(d) {
  const key = d.key;
  switch (d.control.type) {
    case "toggle":
      return { type: "toggle", key };
    case "dropdown":
      return { type: "dropdown", key, options: d.control.options };
    case "text":
      return {
        type: "text",
        key,
        placeholder: d.control.placeholder,
        validate: d.control.validate
      };
  }
}
